ARG OPENJDK_VERSION=11

FROM eclipse-temurin:${OPENJDK_VERSION}

ARG PYSPARK_VERSION=3.2.0

# Install Python and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip python-is-python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install PySpark
RUN pip3 --no-cache-dir install --break-system-packages pyspark==${PYSPARK_VERSION}

WORKDIR /app

COPY . .

CMD ["python3", "main.py"]
